services:
  - type: web
    name: seo-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      mkdir -p /data && \
      chmod 777 /data && \
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
