services:
  - type: web
    name: seo-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: seo_tracker_db
          property: connectionString
    databases:
      - name: seo_tracker_db
        plan: free
        ipAllowList: []
